version: '3'
services:
  rabbitmq:
    container_name: local-test-rabbit
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: local-test
      RABBITMQ_DEFAULT_PASS: local-test
