version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            go install
      - run:
          name: Build
          command: |
            go build
      - run:
          name: Run Tests
          command: |
            go test

  publish-helm:
    docker:
      - image: hypnoglow/helm-s3:master-helm3.4
    steps:
      - checkout
      - run:
          name: Test S3 Access
          command: |
            aws s3api list-objects --bucket=helm.demery.com.au
      - run:
          name: Add Repo
          command: |
            helm repo add demery-helm s3://helm.demery.com.au
            helm repo list
      - run:
          name: Package Chart
          command: |
            helm package ./helm --version=$CIRCLE_TAG --app-version=$CIRCLE_TAG
      - run:
          name: Publish Chart
          command: |
            helm s3 push ./rabbitmq-publish-cron-$CIRCLE_TAG.tgz demery-helm

  publish-docker-beta:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=demery/rabbitmq-publish-cron
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG

  publish-docker:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=demery/rabbitmq-publish-cron
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG .
            docker tag $REGISTRY:$TAG $REGISTRY:latest
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG
            docker push $REGISTRY:latest

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish-docker-beta:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/
      - publish-docker:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
      - publish-helm:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*.*/
            branches:
              ignore: /.*/
          context: s3-helm-deploy
